output_file_name = 'data.csv'
driver_path = '/Users/bhakti/Downloads/chromedriver'
subjects = ["AANL",
            "AASR",
            "AKKD",
            "AMER",
            "ANCM",
            "ANTH",
            "ARAB",
            "ARAM",
            "ARCH",
            "ARME",
            "ARTH",
            "ARTV",
            "ASLG",
            "ASTR",
            "BANG",
            "BASQ",
            "BCMB",
            "BCSN",
            "BIBL",
            "BIOS",
            "BPHS",
            "BPRO",
            "BSDG",
            "BSSR",
            "BULG",
            "BUSF",
            "BUSN",
            "BUSV",
            "CAAM",
            "CABI",
            "CATA",
            "CCTS",
            "CHDV",
            "CHEM",
            "CHIN",
            "CHSS",
            "CHST",
            "CLAS",
            "CLCV",
            "CMES",
            "CMLT",
            "CMSC",
            "CMST",
            "CPNS",
            "CPPE",
            "CRES",
            "CRSH",
            "CRWR",
            "CZEC",
            "DATA",
            "DIGS",
            "DVBI",
            "DVPR",
            "EALC",
            "ECEV",
            "ECMA",
            "ECON",
            "EDSO",
            "EEUR",
            "EGPT",
            "ENGL",
            "ENSC",
            "ENST",
            "EVOL",
            "FNDL",
            "FREN",
            "GEEZ",
            "GENE",
            "GEOG",
            "GEOR",
            "GEOS",
            "GLST",
            "GNSE",
            "GREK",
            "GRMN",
            "HCHR",
            "HEBR",
            "HGEN",
            "HIJD",
            "HIND",
            "HIPS",
            "HIST",
            "HLTH",
            "HMRT",
            "HREL",
            "HSTD",
            "HUMA",
            "IMMU",
            "INRE",
            "INST",
            "ISHU",
            "ISLM",
            "ITAL",
            "JAPN",
            "JWSC",
            "JWSG",
            "KAZK",
            "KNOW",
            "KORE",
            "LACS",
            "LATN",
            "LAWS",
            "LGLN",
            "LING",
            "LLSO",
            "MAAD",
            "MACS",
            "MAPH",
            "MAPS",
            "MARA",
            "MATH",
            "MDVL",
            "MEDC",
            "MENG",
            "MGCB",
            "MICR",
            "MOGK",
            "MOLM",
            "MOMN",
            "MPCS",
            "MPHY",
            "MPMM",
            "MUSI",
            "NCDV",
            "NEAA",
            "NEHC",
            "NELC",
            "NELG",
            "NORW",
            "NSCI",
            "NSFP",
            "NTSC",
            "NURB",
            "ORGB",
            "PALI",
            "PARR",
            "PATH",
            "PBHS",
            "PBPL",
            "PERS",
            "PHIL",
            "PHSC",
            "PHYS",
            "PLSC",
            "POLI",
            "PORT",
            "PPHA",
            "PSMS",
            "PSYC",
            "PWAY",
            "RAME",
            "REES",
            "REMS",
            "RETH",
            "RLIT",
            "RLLT",
            "RLST",
            "RLVC",
            "RUSS",
            "SABR",
            "SALC",
            "SANS",
            "SCTH",
            "SIGN",
            "SLAV",
            "SMSP",
            "SOCI",
            "SOSC",
            "SOSL",
            "SPAN",
            "SSAD",
            "STAT",
            "SUAS",
            "SUMR",
            "SWAH",
            "TAML",
            "TAPS",
            "TBTN",
            "THEO",
            "TLGU",
            "TTIC",
            "TURK",
            "UGAR",
            "URDU",
            "UTEP",
            "UZBK",
            "WOLO",
            "YDDH"]

names = ["Ancient Anatolian Languages",
        "Anthro/Sociology of Religion",
        "Akkadian",
        "American Culture",
        "Ancient Mediterranean World",
        "Anthropology",
        "Arabic",
        "Aramaic",
        "Architectural Studies",
        "Armenian",
        "Art History",
        "Visual Arts",
        "American Sign Language",
        "Astronomy/Astrophysics",
        "Bangla",
        "Basque",
        "Biochemistry/Molecular Biology",
        "Bosnian/Croatian/Serbian",
        "Biblical Studies",
        "Biological Sciences (College)",
        "Biophysical Sciences",
        "Big Problems",
        "Biological Sciences (Graduate)",
        "BSCD Summer Research",
        "Bulgarian",
        "Business",
        "Business",
        "Business",
        "Computational and Applied Math",
        "Cancer Biology",
        "Catalan",
        "Clinical/Translational Science",
        "Comparative Human Development",
        "Chemistry",
        "Chinese",
        "Conceptual/Hist Studies of Sci",
        "Chicago Studies",
        "Classics",
        "Classical Civilization",
        "Middle Eastern Studies",
        "Comparative Literature",
        "Computer Science",
        "Cinema/Media Studies",
        "Computational Neuroscience",
        "Pathway Program in Economics",
        "Comp Race/Ethnic Studies",
        "CIC CourseShare",
        "Creative Writing",
        "Czech",
        "Data Science",
        "Digital Humanities",
        "Developmental Biology",
        "Philosophy of Religions",
        "East Asian Languages/Civ",
        "Ecology/Evolution",
        "Economics (ECMA)",
        "Economics",
        "Education and Society",
        "East European",
        "Egyptian",
        "English Language/Literature",
        "Environmental Sciences",
        "Environmental/Urban Studies",
        "Evolutionary Biology",
        "Fundamentals: Issues/Texts",
        "French",
        "Ge'ez",
        "Genetics",
        "Geographical Sciences",
        "Georgian",
        "Geophysical Sciences",
        "Global Studies",
        "Gender/Sexuality Studies",
        "Greek",
        "German",
        "History of Christianity",
        "Hebrew",
        "Human Genetics",
        "History of Judaism",
        "Hindi",
        "HIPS",
        "History",
        "Health and Society",
        "Human Rights",
        "History of Religions",
        "Health Studies",
        "Humanities",
        "Immunology",
        "International Relations",
        "International Studies",
        "Humanities Interdisc Studies",
        "Islamic Studies",
        "Italian",
        "Japanese",
        "Jewish Studies",
        "Committee on Jewish Studies",
        "Kazak",
        "KNOW",
        "Korean",
        "Latin Amer/Caribbean Studies",
        "Latin",
        "Laws",
        "Languages in Linguistics",
        "Linguistics",
        "Law/Letters/Society",
        "Media Arts and Design",
        "Computational Social Science",
        "MAPH (MA in Humanities)",
        "MAPSS (MA in Social Sciences)",
        "Marathi",
        "Mathematics",
        "Medieval Studies",
        "Medicine",
        "Molecular Engineering",
        "Molecular Genetics/Cell Bio",
        "Microbiology",
        "Modern Greek",
        "Molecular Medicine",
        "Molecular Metabolism/Nutrition",
        "Computer Science Masters",
        "Medical Physics",
        "Molecular Pathogenesis/Med",
        "Music",
        "New Collegiate Division",
        "Near Eastern Art/Archeology",
        "Near Eastern History/Civ",
        "Near Eastern Languages/Civ",
        "Near Eastern Languages",
        "Norwegian",
        "Neuroscience",
        "NSF",
        "Natural Science",
        "Neurobiology",
        "Organismal Biology/Anatomy",
        "Pali",
        "Parrhesia Public Discourse",
        "Pathology",
        "Public Health Sciences",
        "Public Policy Studies (PBPL)",
        "Persian",
        "Philosophy",
        "Physical Science",
        "Physics",
        "Political Science",
        "Polish",
        "Portuguese",
        "Public Policy Studies (PPHA)",
        "Physical Sciences Masters",
        "Psychology",
        "Pathway Program",
        "Religions in America",
        "Russian/East European Studies",
        "Ren/Early Modern Studies",
        "Religious Ethics",
        "Religion/Literature",
        "Romance Languages/Literature",
        "Religious Studies",
        "Religion/Lit/Visual Culture",
        "Russian",
        "Study Abroad",
        "South Asian Languages/Civ",
        "Sanskrit",
        "Social Thought",
        "Signature Courses",
        "General Slavic",
        "Summer Special Programs",
        "Sociology",
        "Social Sciences",
        "South Slavic",
        "Spanish",
        "Social Service Administration",
        "Statistics",
        "Summer Arts & Sciences",
        "Sumerian",
        "Swahili",
        "Tamil",
        "Theater/Performance Studies",
        "Tibetan",
        "Theology",
        "Telegu",
        "Toyota Tech Inst at Chicago",
        "Turkish",
        "Ugaritic",
        "Urdu",
        "Urban Teacher Education",
        "Uzbek",
        "Wolof",
        "Yiddish"]

years = ["2014",
        "2015",
        "2016",
        "2017",
        "2018",
        "2019",
        "2020"]

terms = ["Summer",
        "Spring",
        "Autumn",
        "Winter"]
        
opentype = 'w' # w or a depending on write or append